services:
  gzctf:
    build: .
    container_name: gzctf-app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8080
      ConnectionStrings__Database: Host=db;Port=5432;Database=gzctf;Username=postgres;Password=admin@owasp
      RedisCache: redis:6379,password=admin@owasp
    volumes:
      - gzctf-files:/app/files
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: gzctf-db
    environment:
      POSTGRES_DB: gzctf
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin@owasp
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: gzctf-redis
    command: ["redis-server", "--requirepass", "admin@owasp"]
    restart: unless-stopped

volumes:
  pgdata:
  gzctf-files:
